[package]
name = "juniper-sqlx-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
juniper = "0.15.11"
tokio = { version = "1.25.0", features = ["full"] }
