-- DO NOT EDIT. This file is generated by psqldef. See https://github.com/k0kubun/sqldef
-- command: psqldef -h localhost -U postgres juniper-sqlx --export

CREATE TYPE "actor_role" AS ENUM ('viewer', 'editor', 'admin');

CREATE TABLE "public"."_sqlx_migrations" (
    "version" bigint NOT NULL,
    "description" text NOT NULL,
    "installed_on" timestamp with time zone NOT NULL DEFAULT now(),
    "success" boolean NOT NULL,
    "checksum" bytea NOT NULL,
    "execution_time" bigint NOT NULL,
    PRIMARY KEY ("version")
);

CREATE TABLE "public"."actors" (
    "id" serial NOT NULL,
    "name" character varying(255) NOT NULL,
    "role" actor_role NOT NULL DEFAULT 'viewer'::actor_role,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

CREATE TABLE "public"."posts" (
    "id" serial NOT NULL,
    "title" character varying(255) NOT NULL,
    "actor_id" integer NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT now(),
    "updated_at" timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);

ALTER TABLE ONLY "public"."posts" ADD CONSTRAINT "posts_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "public"."actors" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
